[package]
name = "quadprog"
version = "0.1.0"
authors = ["Ashkan Kiani <from-crates.quadprog@kiani.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14.0"
anyhow = "1.0.41"
ndarray-linalg = "0.13.1"
